#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git diff HEAD --quiet || 
(
  echo "You have uncommitted changes. Please commit them and try again."
  false;
)

yarn test || 
(
  echo "Tests failed. Please fix the errors and try again."
  false;
)

echo "All checks passed. Committing..."